### ISSUE TITLE
本地测试失败，出现这个

### ISSUE THREAD

**Issue by GCParr0t** [ReaJason/17wanxiaoCheckin#79]
2022-01-17 00:19:41 - [INFO] - 正在为 X 打卡......
2022-01-17 00:19:41 - [INFO] - 1980，登录成功
2022-01-17 00:19:42 - [INFO] - 欣-江苏海洋大学，获取个人信息成功
2022-01-17 00:19:42 - [INFO] - 完美校园第一类健康打卡post参数获取成功
Traceback (most recent call last):
  File "C:\Users\N\Documents\GitHub\17wanxiaoCheckin\index.py", line 217, in <module>
    main_handler(user_config_path=user_config_path, push_config_path=push_config_path)
  File "C:\Users\N\Documents\GitHub\17wanxiaoCheckin\index.py", line 204, in main_handler
    check_dict = check_in(user_config)
  File "C:\Users\N\Documents\GitHub\17wanxiaoCheckin\index.py", line 107, in check_in
    healthy1_check_dict = healthy1_check_in(token, user['phone'], post_dict)
  File "C:\Users\N\Documents\GitHub\17wanxiaoCheckin\api\healthy1_check.py", line 95, in healthy1_check_in
    "deptid": post_dict['deptStr']['deptid'] if post_dict['deptStr'] else None,
TypeError: string indices must be integers

**Comment by ReaJason** [comment]
deptStr 的格式是 map 不是 string,你配置文件这个值不对

**Comment by GCParr0t** [comment]
> deptStr 的格式是 map 不是 string,你配置文件这个值不对

我只修改了json，抓包的也抓了，按着上面来的，其他的没动，环境是python3.9，就出现这个问题，迷
