### ISSUE TITLE
偶尔某个时间会出现错误

### ISSUE THREAD

**Issue by Lzhjk1** [ReaJason/17wanxiaoCheckin#86]
```
2022-04-20 08:08:09 - [INFO] - 正在为 --- 打卡......
2022-04-20 08:08:12 - [INFO] - 1897，登录成功
2022-04-20 08:08:13 - [INFO] - ---中南林业科技大学，获取个人信息成功
2022-04-20 08:08:15 - [INFO] - 完美校园第一类健康打卡post参数获取成功
2022-04-20 08:08:16 - [INFO] - {'msg': '成功', 'code': '10000', 'data': 1}
2022-04-20 08:08:16 - [INFO] - 当前并未开启校内打卡，暂不进行打卡操作
2022-04-20 08:08:17 - [INFO] - 签到成功,今日获得 0 粮票
Traceback (most recent call last):
  File "index.py", line 217, in <module>
    main_handler(user_config_path=user_config_path, push_config_path=push_config_path)
  File "index.py", line 204, in main_handler
    check_dict = check_in(user_config)
  File "index.py", line 168, in check_in
    for task in task_list:
TypeError: 'NoneType' object is not iterable
```
这两个月出现了两次，今天是第二次
打卡成功了，但是还没有推送邮箱消息
Debian 10 ，Python 3.7.3
是放在云服务器上运行的

**Comment by ReaJason** [comment]
这是由于粮票那边的问题，目前还没有修复，请在配置文件中关闭掉粮票开关
